Update man 03
jmf-nyu/miap_diglit pull request #10
Opened 2023-12-01 02:14 UTC by les542

2023-12-03 17:25 UTC, jmf-nyu requested changes
This is mostly looking good with a few small comments on some of the lines.

Most importantly, you will need to edit the index.md file to include a link to your new page for the man command. That file wasn't edited in this pull request. 

Second, you will need to rename your new file to "man.md". The .md extension makes sure that GitHub pages sees this file as a Markdown file.  

Before you revise your pull request, make sure you are fetching and pulling changes from the class repository. I have already merged a few pull requests.

2023-12-03 17:25 UTC, jmf-nyu commented on docs/man
> +$ `man [options] [directory path]`
the second argument in the `man` command structure is the [name of command] not the [directory path]

2023-12-03 17:25 UTC, jmf-nyu commented on docs/man
> +Executable programs or shell commands
This list of sections could be presented as bullets by placing an asterisk before each item.

2023-12-03 17:25 UTC, jmf-nyu commented on docs/man
> +https://www.nielit.gov.in/gorakhpur/sites/default/files/Gorakhpur/Alevel_unix_27april20_AKM.pdf
URLs should be correctly formatted as hyperlinks using the Markdown syntax described in the documentation here: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#links

2023-12-03 17:25 UTC, jmf-nyu commented on docs/man
> +See: Terminal
I'm not sure what this means

2023-12-06 23:12 UTC, les542 commented
Updated the man file to "man.md" to become a markdown file. Did revisions. I forgot to sync the fork beforehand and was concerned about it deleting my changes or 'commits.'

2023-12-07 03:31 UTC, jmf-nyu requested changes
You've fixed some of the issues I've mentioned. Almost there. However, there are still a few more. Please check my comments that refer to various lines of your code. 

Also, keep in mind that by not syncing your fork some conflicts were created. They are simple enough that I can fix them when submit the pull request. Just keep that in mind for the future that you always want to be syncing your fork (i.e., fetching new changes and merging them on your copy of the code) before starting new work to avoid conflicts.

2023-12-07 03:32 UTC, jmf-nyu commented on docs/man
> +https://www.nielit.gov.in/gorakhpur/sites/default/files/Gorakhpur/Alevel_unix_27april20_AKM.pdf
@les542 This hasn't been resolved yet

2023-12-07 03:33 UTC, jmf-nyu commented on docs/man
> +See: Terminal
Please resolve

2023-12-08 00:51 UTC, merged