Create chmod.md
jmf-nyu/miap_diglit pull request #36
Opened 2024-11-19 01:24 UTC by ls6758

2024-11-19 02:02 UTC, jmf-nyu requested changes
Hi Linda,

Overall, this is a good start! I have suggested a few changes to make sure you are using Markdown syntax properly. I will place the pull request in draft mode so you can make additional changes to your repository and they will be reflected here.

Best,
Jonathan

2024-11-19 02:02 UTC, jmf-nyu commented on docs/chmod.md
> +ls -l /var/www/html/omeka/
Well done!

2024-11-19 02:02 UTC, jmf-nyu commented on docs/chmod.md
> +Modes specify the read, write, and execute access, respectively for the three classes of user, group, and others. This is represented as a numerical value, typically either 3 or 4 characters in lengt
It would be nice here to include a hyperlink that explains the different numerical values for `chmod`

2024-11-25 02:41 UTC, jmf-nyu commented
@ls6758 could you resolve the other changes?

2024-11-25 02:47 UTC, ls6758 commented
I thought I already did? All of the changes are made on what I can see in my fork of the repository.

2024-11-26 01:09 UTC, jmf-nyu commented on docs/chmod.md
> +$ sudo chmod [options] mode[,mode] file1 [file2…]
@ls6758 I'm not seeing this formatting correction in your latest commit.

2024-11-26 01:09 UTC, jmf-nyu commented on docs/chmod.md
> +This command does not output a message. The ls or stat command would need to be used in order to show that the changes were made and saved correctly. To check if the change of the root folder permiss
@ls6758 I'm not seeing this formatting change in your latest commit.

2024-11-26 01:11 UTC, jmf-nyu commented on docs/chmod.md
> +Modes specify the read, write, and execute access, respectively for the three classes of user, group, and others. This is represented as a numerical value, typically 3 characters in length. A mode of
In markdown URLs have the format of `[text for link](Full URL)`. Refer to my `ls` page if needed.

2024-12-10 03:54 UTC, merged

2024-12-10 03:54 UTC, jmf-nyu commented
There are still some changes to make, but I'll merge this for now